const express = require("express");
const { loginAdmin, getCurrentAdmin } = require("../controllers/adminController");
const { requireRole } = require("../middleware/auth");
const { getInventory, updateInventory } = require("../controllers/inventoryController");
const { getAdminOrders, getAdminOrder, updateFulfillment } = require("../controllers/adminOrderController");
const router = express.Router();
router.get("/orders", requireRole("admin"), getAdminOrders);
router.get("/orders/:id", requireRole("admin"), getAdminOrder);
router.patch("/orders/:id/status", requireRole("admin"), updateFulfillment);
router.get("/inventory", requireRole("admin"), getInventory);
router.patch("/inventory/:id", requireRole("admin"), updateInventory);
router.post("/login", loginAdmin);
router.get("/me", requireRole("admin"), getCurrentAdmin);
module.exports = router;
